name: Update Gists in Profile

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node-fetch
        run: npm install node-fetch@2
      - name: Update README with Gists
        run: node update-gists.js
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --quiet && echo "No changes to commit" || git commit -m "Update README with latest gists"
          git push
