name: Update Gists in Profile

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readme-templates/latest-gists@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          gist_count: 5
          gist_prefix: "- "
          readme_path: ./README.md
